name: fuzzingbook
channels:
  - defaults
  - anaconda-fusion
  - conda-forge
  - bjornfjohansson
  - anaconda-platform
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - scipy
  - pandas
  - graphviz
  - autopep8
  - notedown
  - markdown
  - mypy
  - selenium
# - geckodriver
  - django
  - pip
  - pip:
      - markdown
      - graphviz
      - isla-solver
      - networkx
      - yapf
      - autopep8
      - svglib
      - jupyter_contrib_nbextensions
      - showast
      - z3-solver
      - git+https://github.com/uds-se/pyan#egg=pyan
      - FuzzManager
